# code/model/persona_academic.py
import json
import logging
import re
from typing import Tuple, Dict, Any, List, Optional

from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage

import conf
from model.conversation_state import ConversationState
from utils.llm_call import llm_invoke
from utils.prompts_academic import SYSTEM_PROMPT as SYSTEM_PROMPT_ACADEMIC

_LOG = logging.getLogger("restbiz.academic")


class AcademicPersonaService:
    """
    Academic Persona (REQUIRED FLOW)
    2.1 Retrieve -> ask REQUIRED SLOTS (dynamic, generated from question + docs)
    2.2 After slots -> ask which SECTIONS (dynamic; only what exists for this case)
    3) Final answer (evidence-only; best-effort)
    4) Mark done for supervisor auto-return

    Production fixes (P0/P1):
    - ✅ Do NOT create academic_flow.stage="idle" automatically
    - ✅ Retrieve ONLY once when starting intake (store academic_question); never re-retrieve on slot replies
    - ✅ Use academic_question for final prompt (never fallback to "1,2" etc.)
    - ✅ Make force_intake meaningful: keep intake stage, re-ask slots on greeting/noise, never reset stage
    - ✅ Stronger greeting/noise detection inside intake (backup safety)
    - ✅ Fix Thai-text false-noise bug (P0): Thai-only responses must NOT be treated as noise
    - ✅ Slots are NOT a numbered menu (P0): do not bind numbers for slot stage
    - ✅ If no sections exist -> answer immediately (P0): do not stall awaiting_sections
    - ✅ NEW: Dynamic slots generated by LLM from user question + docs (not hardcoded template)
    - ✅ NEW: Cross-persona slot memory — skip already-known slots from Practical mode
    - ✅ NEW: Auto-return stores topic context for supervisor to build related topics menu
    - ✅ NEW: LLM call timeout via conf.LLM_REQUEST_TIMEOUT
    """

    persona_id = "academic"

    # For parsing numbered options (used ONLY for section menu, not slots)
    _OPTION_LINE_RE = re.compile(r"(?m)^\s*(\d{1,2})\s*[\)\.\:]\s*(.+?)\s*$")

    # Detect "ทั้งหมด"
    _SELECT_ALL_RE = re.compile(r"(ทั้งหมด|ทุกข้อ|ทุกหัวข้อ|เอาทั้งหมด|all|everything)", re.IGNORECASE)

    # Backup greeting/noise detection (supervisor should already do, but keep safe)
    _TH_LAUGH_RE = re.compile(r"^\s*5{3,}\s*$")
    _EN_GREETING_RE = re.compile(r"^\s*(hi+|hello+|hey+|yo+)\b", re.IGNORECASE)
    _EN_GOOD_TIME_RE = re.compile(r"^\s*good\s+(morning|afternoon|evening|night)\b", re.IGNORECASE)
    _TH_SAWASDEE_FUZZY_RE = re.compile(r"^\s*สว[^\s]{0,6}ดี", re.IGNORECASE)
    _TH_WATDEE_RE = re.compile(r"^\s*หวัดดี", re.IGNORECASE)
    _FILLER_ONLY_RE = re.compile(r"^\s*(ครับ|คับ|ค่ะ|คะ|จ้า|จ้ะ|ค่า|งับ)\s*$", re.IGNORECASE)

    # IMPORTANT P0:
    # Do NOT treat Thai-only text as noise.
    # Only treat as noise when:
    # - very short AND only punctuation/symbols, OR
    # - single repeated character patterns, OR
    # - meaningless latin-only fragments (very short)
    _PUNCT_ONLY_RE = re.compile(r"^\s*[!?.…。，、\-_=+*/\\|@#$%^&*(){}\[\]<>\"'`~:;]+?\s*$")
    _REPEATED_CHAR_RE = re.compile(r"^\s*(.)\1{6,}\s*$")  # e.g., "aaaaaaa", "!!!!!!", "รรรรรรร"
    _LATIN_GIBBERISH_RE = re.compile(r"^\s*[a-z]{1,8}\s*$", re.IGNORECASE)  # tiny latin-only token

    def __init__(self, retriever):
        self.retriever = retriever
        self._init_llm()

    def _init_llm(self):
        model_name = getattr(conf, "OPENROUTER_MODEL_ACADEMIC", conf.OPENROUTER_MODEL)
        timeout = int(getattr(conf, "LLM_REQUEST_TIMEOUT", 30))
        self.llm = ChatOpenAI(
            model=model_name,
            openai_api_key=conf.OPENROUTER_API_KEY,
            openai_api_base=conf.OPENROUTER_BASE_URL,
            temperature=getattr(conf, "TEMPERATURE_ACADEMIC", 0.3),
            max_tokens=getattr(conf, "MAX_TOKENS_ACADEMIC", 8000),
            request_timeout=timeout,
            model_kwargs={"response_format": {"type": "json_object"}},
        )
        # Separate LLM for slot generation.
        # GPT-5.1 is a thinking model — reasoning tokens eat into the budget first.
        # MAX_TOKENS_ACADEMIC_SLOTS (default 3000) gives room for reasoning + actual JSON output.
        slots_max_tokens = getattr(conf, "MAX_TOKENS_ACADEMIC_SLOTS", 3000)
        self.llm_slots = ChatOpenAI(
            model=model_name,
            openai_api_key=conf.OPENROUTER_API_KEY,
            openai_api_base=conf.OPENROUTER_BASE_URL,
            temperature=0.1,
            max_tokens=slots_max_tokens,
            request_timeout=timeout,
            model_kwargs={"response_format": {"type": "json_object"}},
        )

    # ----------------------------
    # Safe append (dedupe) - prefer state helpers when available
    # ----------------------------
    def _append_user_once(self, state: ConversationState, content: str) -> None:
        if hasattr(state, "add_user_message_once"):
            state.add_user_message_once(content)
            return
        if content is None:
            return
        c = str(content)
        if not c.strip():
            return
        if state.messages and state.messages[-1].get("role") == "user" and (state.messages[-1].get("content") or "") == c:
            return
        state.messages.append({"role": "user", "content": c})

    def _append_assistant(self, state: ConversationState, content: str) -> None:
        if hasattr(state, "add_assistant_message_once"):
            state.add_assistant_message_once(content)
            return
        if content is None:
            return
        c = str(content).strip()
        if not c:
            return
        state.messages = state.messages or []
        if state.messages:
            last = state.messages[-1]
            if last.get("role") == "assistant" and (last.get("content") or "").strip() == c:
                return
        state.messages.append({"role": "assistant", "content": c})

    # ----------------------------
    # Context helpers (flow)
    # ----------------------------
    def _get_flow(self, state: ConversationState) -> Optional[Dict[str, Any]]:
        """
        IMPORTANT (P0):
        - Do NOT create flow on read.
        - Return None if flow not started yet.
        """
        state.context = state.context or {}
        flow = state.context.get("academic_flow")
        if isinstance(flow, dict) and str(flow.get("stage") or "").strip():
            return flow
        return None

    def _ensure_flow(self, state: ConversationState, stage: str, **kwargs) -> Dict[str, Any]:
        """
        Create/overwrite flow only when we truly start intake or update a known stage.
        """
        state.context = state.context or {}
        flow = state.context.get("academic_flow")
        if not isinstance(flow, dict):
            flow = {}
        flow["stage"] = stage
        flow.update(kwargs)
        state.context["academic_flow"] = flow
        return flow

    def _set_flow(self, state: ConversationState, **kwargs) -> None:
        """
        Update flow if it exists; create only if 'stage' provided.
        """
        state.context = state.context or {}
        flow = state.context.get("academic_flow")
        if not isinstance(flow, dict):
            flow = {}
        if "stage" in kwargs and kwargs.get("stage"):
            flow["stage"] = kwargs.get("stage")
        for k, v in kwargs.items():
            if k == "stage":
                continue
            flow[k] = v
        if str(flow.get("stage") or "").strip():
            state.context["academic_flow"] = flow

    def _mark_done(self, state: ConversationState) -> None:
        self._set_flow(state, stage="done")
        state.context["auto_return_to_practical"] = True
        # Store topic context so supervisor can build a related-topics menu on auto-return
        topic_ctx = (state.context or {}).get("academic_question", "")
        if topic_ctx:
            state.context["auto_return_topic_context"] = topic_ctx

    # ----------------------------
    # Greeting/noise (backup safety)
    # ----------------------------
    def _looks_like_greeting_or_noise(self, user_text: str) -> bool:
        raw = (user_text or "").strip()
        if not raw:
            return True
        if self._TH_LAUGH_RE.match(raw):
            return True
        if self._FILLER_ONLY_RE.match(raw):
            return True

        low = raw.lower().strip()
        if self._EN_GREETING_RE.match(low) or self._EN_GOOD_TIME_RE.match(low):
            return True
        if self._TH_WATDEE_RE.match(raw) or self._TH_SAWASDEE_FUZZY_RE.match(raw):
            return True

        # P0: do NOT treat Thai-only as noise. Only detect truly noisy patterns.
        if len(raw) <= 16:
            if self._PUNCT_ONLY_RE.match(raw):
                return True
            if self._REPEATED_CHAR_RE.match(raw):
                return True
            if self._LATIN_GIBBERISH_RE.match(raw):
                return True

        return False

    # ----------------------------
    # Retrieval (only once per intake)
    # ----------------------------
    def _retrieve_docs(self, query: str) -> List[Dict[str, Any]]:
        docs = self.retriever.invoke(query)
        results: List[Dict[str, Any]] = []
        for d in (docs or [])[: int(getattr(conf, "RETRIEVAL_TOP_K", 20) or 20)]:
            results.append(
                {
                    "content": (getattr(d, "page_content", "") or "")[:600],
                    "metadata": getattr(d, "metadata", {}) or {},
                }
            )
        return results

    def _start_intake_with_retrieval(self, state: ConversationState, user_question: str) -> None:
        """
        P0: Retrieve only here (once), store academic_question, set last_retrieval_query.
        FIX: use conf.DEFAULT_RETRIEVAL_FALLBACK_QUERY as single source of truth for fallback.
        Reuse state.current_docs when already populated by supervisor entity-type filter.
        """
        q = (user_question or "").strip()
        if not q:
            q = getattr(conf, "DEFAULT_RETRIEVAL_FALLBACK_QUERY",
                        "กฎหมายร้านอาหาร ใบอนุญาต ภาษี VAT จดทะเบียน สุขาภิบาล ประกันสังคม")

        state.context = state.context or {}

        # Enrich query with entity type if already known (from practical slot memory)
        if hasattr(state, "get_collected_slots"):
            slots = state.get_collected_slots() or {}
            for v in slots.values():
                sv = str(v).strip()
                if any(kw in sv for kw in ("นิติบุคคล", "บุคคลธรรมดา")):
                    if sv not in q:
                        q = f"{q} {sv}"
                    break

        state.context["academic_question"] = q

        # Reuse pre-retrieved docs from supervisor (e.g. entity-type filtered) if already populated.
        # Only retrieve fresh when state.current_docs is empty or too few.
        if len(state.current_docs or []) >= 2:
            _LOG.info("[Academic] Reusing %d pre-retrieved docs from supervisor", len(state.current_docs))
        else:
            state.current_docs = self._retrieve_docs(q)

        if hasattr(state, "set_last_retrieval_query"):
            state.set_last_retrieval_query(q, cache_to_context=True)
        else:
            state.last_retrieval_query = q
            state.context["last_retrieval_query"] = q

    # ----------------------------
    # Option parsing / binding (ONLY for section menu)
    # ----------------------------
    def _extract_numbered_options(self, text: str) -> Dict[int, str]:
        options: Dict[int, str] = {}
        for m in self._OPTION_LINE_RE.finditer(text or ""):
            try:
                k = int(m.group(1))
                v = (m.group(2) or "").strip()
                if v:
                    options[k] = v
            except Exception:
                continue
        return options

    def _parse_numbers(self, user_text: str) -> List[int]:
        if not user_text:
            return []
        nums = [int(x) for x in re.findall(r"\d{1,2}", user_text)]
        nums = [n for n in nums if 0 < n < 100]
        seen = set()
        out = []
        for n in nums:
            if n not in seen:
                seen.add(n)
                out.append(n)
        return out

    def _is_select_all(self, user_text: str) -> bool:
        return bool(self._SELECT_ALL_RE.search(user_text or ""))

    def _bind_choice_if_any(self, state: ConversationState, user_text: str) -> Dict[str, Any]:
        """
        Binder for SECTION stage only.
        Uses state.context["pending_options"] generated by _ask_sections().
        """
        ctx = state.context or {}
        pending = ctx.get("pending_options") or {}
        if not isinstance(pending, dict) or not pending:
            return {"bound": False}

        if self._is_select_all(user_text):
            keys = sorted([int(k) for k in pending.keys() if str(k).isdigit()])
            resolved = [f"{k}) {pending.get(k)}" for k in keys]
            ctx["resolved_selection"] = {"type": "all", "selected": keys, "resolved": resolved, "raw": user_text}
            ctx["pending_options"] = {}
            ctx["pending_question"] = ""
            state.context = ctx
            return {"bound": True, "mode": "all", "selected": keys}

        nums = self._parse_numbers(user_text)
        if not nums:
            return {"bound": False}

        valid = [n for n in nums if n in pending]
        if not valid:
            return {"bound": False, "reason": "numbers_not_in_options"}

        # If any selected option is "ทั้งหมด" → treat as select-all
        if any(str(pending.get(n, "")).strip() == "ทั้งหมด" for n in valid):
            keys = sorted([int(k) for k in pending.keys() if str(k).isdigit()])
            resolved = [f"{k}) {pending.get(k)}" for k in keys if str(pending.get(k, "")).strip() != "ทั้งหมด"]
            ctx["resolved_selection"] = {"type": "all", "selected": keys, "resolved": resolved, "raw": user_text}
            ctx["pending_options"] = {}
            ctx["pending_question"] = ""
            state.context = ctx
            return {"bound": True, "mode": "all", "selected": keys}

        resolved = [f"{n}) {pending[n]}" for n in valid]
        ctx["resolved_selection"] = {"type": "numbers", "selected": valid, "resolved": resolved, "raw": user_text}
        ctx["pending_options"] = {}
        ctx["pending_question"] = ""
        state.context = ctx
        return {"bound": True, "mode": "numbers", "selected": valid}

    # ----------------------------
    # Stage 2.1: dynamic slots (LLM-generated from question + docs)
    # ----------------------------
    # Fields to include in slot generation prompt (reduces prompt tokens significantly)
    _SLOT_PROMPT_META_KEYS = (
        "topic_name", "short_name", "regulation_name", "target_audience",
        "conditions_applicability", "entity_type", "location_scope",
    )

    def _build_slot_generation_prompt(self, user_question: str, docs: List[Dict], known_slots: Dict[str, str]) -> str:
        # Use only 3 docs, key metadata fields + content snippet, 120-char limit per value
        doc_summary = []
        for d in (docs or [])[:3]:
            raw_md = d.get("metadata") or {}
            md = {}
            for key in self._SLOT_PROMPT_META_KEYS:
                v = raw_md.get(key)
                if v and str(v).strip() and str(v).lower() != "nan":
                    md[key] = str(v).strip()[:120]
            # Include a short content snippet so LLM can detect branching cases
            # (e.g. "นายจ้างบุคคลธรรมดา", "ลูกจ้างใหม่", "ลูกจ้างที่เคยมีสิทธิ์") in the actual text
            snippet = (d.get("content") or "")[:200].strip()
            if snippet:
                md["_content"] = snippet
            if md:
                doc_summary.append(md)

        known_str = json.dumps(known_slots, ensure_ascii=False) if known_slots else "{}"
        docs_str = json.dumps(doc_summary, ensure_ascii=False)

        return f"""หน้าที่: วิเคราะห์คำถามและเอกสาร แล้วสร้าง "ข้อมูลบริบทที่ต้องถาม" เพื่อให้ตอบถูกกรณีตามกฎหมาย

คำถามผู้ใช้: {user_question}

ข้อมูลที่รู้แล้ว (ห้ามถามซ้ำ): {known_str}
(หมายเหตุ: key อาจต่างกันแต่ความหมายเหมือนกัน เช่น registration_type / entity_type / business_type ล้วนหมายถึงประเภทกิจการ ให้ถือว่ารู้แล้วถ้า value ตรงกัน)

ตัวอย่าง metadata + เนื้อหาจากเอกสาร: {docs_str}

กติกา:
- ถามเฉพาะ "บริบทของผู้ใช้" ที่ทำให้ตอบถูกกรณีกฎหมาย เช่น ประเภทกิจการ, สถานะผู้ใช้, จำนวนลูกจ้าง, ที่ตั้ง, รายได้
- ถ้าเอกสารมีกรณีแยกชัดเจน (เช่น ลูกจ้างใหม่ vs ลูกจ้างที่เคยมีประกันสังคม, ออนไลน์ vs ยื่นตรง) ให้ถามว่า user อยู่ในกรณีไหน
- ห้ามถาม "หัวข้อ/ส่วนที่อยากรู้" เช่น ขั้นตอน/เอกสาร/ค่าธรรมเนียม/ระยะเวลา — ระบบจัดการส่วนนี้แยกต่างหากแล้ว
- ถ้ามีตัวเลือกชัดเจนจากเอกสาร ให้ใส่ใน choices
- ถ้าไม่มีตัวเลือกชัดเจน ให้ choices เป็น null
- ห้ามเกิน 3 ข้อ
- ภาษาไทย สุภาพ เข้าใจง่าย เหมาะกับคนทั่วไป (ไม่ใช่ภาษากฎหมาย)
- ถ้าคำถามที่ user ถามเฉพาะเจาะจงมากพอแล้ว อาจไม่ต้องถาม slot เลยก็ได้ (return slots เป็น list ว่าง)

ตอบเป็น JSON เท่านั้น:
{{"slots": [{{"key": "entity_type", "question": "ดำเนินกิจการในนามบุคคลธรรมดาหรือนิติบุคคลครับ?", "choices": ["บุคคลธรรมดา", "นิติบุคคล (บริษัท/ห้างหุ้นส่วน)"]}}]}}"""

    def _parse_slots_llm_response(self, raw: str) -> List[Dict]:
        """Parse LLM JSON response into list of slot dicts. Returns [] on failure."""
        text = (raw or "").strip()
        if "```json" in text:
            text = text.split("```json")[1].split("```")[0].strip()
        elif "```" in text:
            text = text.split("```")[1].split("```")[0].strip()
        try:
            result = json.loads(text)
            if isinstance(result, dict):
                return result.get("slots") or []
        except Exception:
            pass
        return []

    _CHOICE_LABELS = ("ก", "ข", "ค", "ง")

    def _render_slot_message(self, needed: List[Dict], state: Optional["ConversationState"] = None) -> str:
        """Build the slot question message. Stores per-slot and global choice maps in state."""
        lines = ["เพื่อตอบได้ตรงกรณีของคุณ รบกวนตอบรวดเดียวครับ (ตอบเท่าที่รู้)"]
        choice_map: Dict[str, str] = {}          # global fallback label → text
        slot_choice_maps: Dict[str, Dict[str, str]] = {}  # slot_key → {label → text}
        for i, slot in enumerate(needed, 1):
            q_text = (slot.get("question") or "").strip()
            if not q_text:
                continue
            key = slot.get("key") or f"slot_{i}"
            choices = slot.get("choices") or []
            lines.append(f"{i}) {q_text}")
            per_slot: Dict[str, str] = {}
            for j, c in enumerate(choices[:4]):
                lbl = self._CHOICE_LABELS[j]
                lines.append(f"   {lbl}) {c}")
                per_slot[lbl] = c
                per_slot[lbl.lower()] = c
                # global map: last-write wins (used only for single-question fallback)
                choice_map[lbl] = c
                choice_map[lbl.lower()] = c
            slot_choice_maps[key] = per_slot
        if state is not None:
            ctx = state.context or {}
            if slot_choice_maps:
                ctx["dynamic_slot_choice_maps"] = slot_choice_maps  # per-slot (authoritative)
            if choice_map:
                ctx["dynamic_slot_choice_map"] = choice_map          # global (backward compat)
            state.context = ctx
        return "\n".join(lines)

    def _generate_dynamic_slots(self, state: ConversationState) -> str:
        """
        Generate slot questions dynamically using LLM based on:
        - user's actual question
        - retrieved documents (lean metadata only)
        - already-known slots (from cross-persona memory)

        Strategy A (primary): lean prompt → GPT-5.1 with MAX_TOKENS_ACADEMIC_SLOTS
        Strategy B (retry fallback): question-only prompt → same model, minimal context
        Returns empty string ONLY when all slots already known / question is specific enough.
        Never silently skips slots due to LLM error — always retries before giving up.
        """
        ctx = state.context or {}
        user_q = ctx.get("academic_question", "")
        known_slots = state.get_collected_slots() if hasattr(state, "get_collected_slots") else {}

        # ── Strategy A: lean prompt (key metadata fields only, 3 docs max) ──
        prompt_a = self._build_slot_generation_prompt(user_q, state.current_docs or [], known_slots)
        slots_data: List[Dict] = []
        try:
            resp = llm_invoke(self.llm_slots, [HumanMessage(content=prompt_a)], logger=_LOG, label="Academic/slots", state=state)
            slots_data = self._parse_slots_llm_response(resp.content or "")
        except Exception as e:
            _LOG.warning("[Academic] Slot generation (A) failed: %s — retrying with lean prompt", e)

        # ── Strategy B: question-only prompt (no metadata, smallest possible prompt) ──
        if not slots_data:
            known_str = json.dumps(known_slots, ensure_ascii=False) if known_slots else "{}"
            prompt_b = (
                f"หน้าที่: สร้างคำถามที่จำเป็นเพื่อให้ตอบคำถามนี้ได้ตรงกรณี\n"
                f"คำถามผู้ใช้: {user_q}\n"
                f"ข้อมูลที่รู้แล้ว (ห้ามถามซ้ำ): {known_str}\n\n"
                f"กติกา:\n"
                f"- สร้างเฉพาะคำถามที่จำเป็นต่อหัวข้อนี้ ห้ามเกิน 4 ข้อ\n"
                f"- ถ้าคำถาม user เฉพาะเจาะจงพอแล้ว ให้ return slots เป็น list ว่าง\n"
                f"ตอบ JSON เท่านั้น:\n"
                f'[{{"key":"location","question":"ร้านตั้งอยู่ที่ไหนครับ?","choices":["กรุงเทพฯ","ต่างจังหวัด"]}}]'
                f'\nรูปแบบ: {{"slots": [...]}}'
            )
            try:
                resp_b = llm_invoke(self.llm_slots, [HumanMessage(content=prompt_b)], logger=_LOG, label="Academic/slots_retry", state=state)
                slots_data = self._parse_slots_llm_response(resp_b.content or "")
            except Exception as e2:
                _LOG.warning("[Academic] Slot generation (B) also failed: %s", e2)

        # Filter out already-known slot keys
        needed = [s for s in slots_data
                  if isinstance(s, dict) and s.get("key") and s["key"] not in known_slots]

        if not needed:
            # LLM confirmed no slots needed (question specific enough) OR both attempts failed
            if not slots_data:
                # Both LLM calls failed entirely — log warning but do NOT silently skip
                _LOG.error("[Academic] Both slot generation attempts failed — proceeding to section menu")
            else:
                _LOG.info("[Academic] No slots needed (all known or question is specific)")
            return ""

        # Build message (pass state so choice_map gets stored for label resolution)
        msg = self._render_slot_message(needed, state=state)

        # Store slot keys for later context enrichment
        state.context["dynamic_slot_keys"] = [s.get("key") for s in needed if s.get("key")]
        state.context["pending_options"] = {}
        state.context["pending_question"] = ""
        self._set_flow(state, stage="awaiting_slots")
        return msg

    def _ask_required_slots(self, state: ConversationState) -> str:
        """
        Entry point for slot phase — tries dynamic generation first,
        falls back to topic-aware defaults if LLM unavailable.
        P0: Slots are NOT a selection menu. Do NOT set pending_options here.
        """
        msg = self._generate_dynamic_slots(state)
        if msg:
            return msg
        # Empty string means all slots already known — signal caller to skip to sections
        return ""

    def _save_slots_best_effort(self, state: ConversationState, user_text: str) -> None:
        ctx = state.context or {}
        slots = ctx.get("academic_slots")
        if not isinstance(slots, dict):
            slots = {}

        raw = (user_text or "").strip()
        choice_map = ctx.get("dynamic_slot_choice_map") or {}
        slot_choice_maps = ctx.get("dynamic_slot_choice_maps") or {}  # per-slot (authoritative)
        slot_keys = ctx.get("dynamic_slot_keys") or []

        # Parse multi-answer responses like "ก ค ก" into per-slot values using per-slot maps.
        # Labels repeat across questions (each question has its own ก/ข/ค/ง), so we must use
        # the per-slot map for the i-th answer → i-th slot key.
        if slot_keys and slot_choice_maps:
            tokens = re.split(r"[\s,/]+", raw)
            # Keep only tokens that are valid Thai labels (ก ข ค ง, case-insensitive)
            _valid_labels = set(self._CHOICE_LABELS) | {l.lower() for l in self._CHOICE_LABELS}
            labels = [t for t in tokens if t.strip() in _valid_labels]
            for i, key in enumerate(slot_keys):
                if i >= len(labels):
                    break
                label = labels[i]
                per_map = slot_choice_maps.get(key, {})
                val = per_map.get(label) or per_map.get(label.lower()) or choice_map.get(label) or label
                if val:
                    slots[key] = val
                    try:
                        state.save_collected_slot(key, val)
                    except Exception:
                        pass

        # Fallback: resolve single-label input "ก" → actual text via global map
        resolved_raw = raw
        if choice_map and raw in choice_map:
            resolved_raw = choice_map[raw]

        slots["raw"] = resolved_raw
        ctx["academic_slots"] = slots
        state.context = ctx

    # ----------------------------
    # Stage 2.2: dynamic section menu (only what exists)
    # ----------------------------
    def _available_sections_from_docs(self, state: ConversationState) -> List[Dict[str, str]]:
        docs = state.current_docs or []

        def has_any_metadata(keys: List[str]) -> bool:
            for d in docs:
                md = (d.get("metadata") or {})
                for key in keys:
                    val = md.get(key)
                    if val is None:
                        continue
                    s = str(val).strip()
                    if s and s.lower() != "nan":
                        return True
            return False

        def has_any_content(keywords: List[str]) -> bool:
            # P1: fallback if metadata is missing
            kws = [k for k in (keywords or []) if k]
            if not kws:
                return False
            for d in docs:
                content = (d.get("content") or "")
                for kw in kws:
                    if kw and kw in content:
                        return True
            return False

        candidates = [
            (
                ["operation_steps", "operation_step", "steps", "procedure", "ขั้นตอนการดำเนินการ"],
                "ขั้นตอนการดำเนินการ",
                ["ขั้นตอน", "ยื่น", "ดำเนินการ", "procedure", "steps"],
            ),
            (
                ["identification_documents", "documents", "required_documents", "เอกสาร ยืนยันตัวตน", "เอกสารที่ต้องใช้"],
                "เอกสารที่ต้องใช้",
                ["เอกสาร", "สำเนา", "แบบฟอร์ม", "documents"],
            ),
            (["fees", "fee", "ค่าธรรมเนียม"], "ค่าธรรมเนียม", ["ค่าธรรมเนียม", "fee", "ชำระ"]),
            (["operation_duration", "duration", "ระยะเวลา การดำเนินการ", "ระยะเวลาดำเนินการ"], "ระยะเวลา", ["ระยะเวลา", "วันทำการ", "duration"]),
            (["service_channel", "channel", "ช่องทางการ ให้บริการ", "ช่องทาง", "หน่วยงาน", "department"], "ช่องทาง/สถานที่ยื่น", ["ช่องทาง", "หน่วยงาน", "สำนักงาน", "department"]),
            (["terms_and_conditions", "conditions", "เงื่อนไขและหลักเกณฑ์"], "เงื่อนไขและหลักเกณฑ์", ["เงื่อนไข", "หลักเกณฑ์", "conditions"]),
            (["legal_regulatory", "law", "regulation", "ข้อกำหนดทางกฎหมาย และข้อบังคับ", "บทลงโทษ"], "ข้อกฎหมาย/ข้อควรระวัง/บทลงโทษ", ["กฎหมาย", "ข้อบังคับ", "บทลงโทษ", "regulation"]),
        ]

        out: List[Dict[str, str]] = []
        for keys, label, kws in candidates:
            if has_any_metadata(keys) or has_any_content(kws):
                out.append({"key": keys[0], "label": label})
        return out

    def _ask_sections(self, state: ConversationState) -> str:
        sections = self._available_sections_from_docs(state)

        if not sections:
            # P0: no sections -> proceed to final immediately (caller will handle)
            state.context["selected_sections"] = {"type": "all", "keys": []}
            state.context["section_catalog"] = []
            state.context["pending_options"] = {}
            state.context["pending_question"] = ""
            self._set_flow(state, stage="no_sections")
            return ""

        lines = ["คุณอยากรู้เรื่องไหนครับ"]
        opts: Dict[int, str] = {}
        for i, sec in enumerate(sections, start=1):
            opts[i] = sec["label"]
            lines.append(f"{i}) {sec['label']}")
        all_n = len(sections) + 1
        opts[all_n] = "ทั้งหมด"
        lines.append(f"{all_n}) ทั้งหมด")

        msg = "\n".join(lines)

        state.context["section_catalog"] = sections
        state.context["pending_options"] = opts
        state.context["pending_question"] = msg
        self._set_flow(state, stage="awaiting_sections")
        return msg

    def _save_selected_sections(self, state: ConversationState, user_text: str, bind_info: Dict[str, Any]) -> None:
        ctx = state.context or {}
        catalog = ctx.get("section_catalog") or []
        if not isinstance(catalog, list):
            catalog = []

        if self._is_select_all(user_text) or (bind_info.get("bound") and bind_info.get("mode") == "all"):
            ctx["selected_sections"] = {"type": "all", "keys": [c.get("key") for c in catalog if c.get("key")]}
            state.context = ctx
            return

        nums = bind_info.get("selected") if bind_info.get("bound") and bind_info.get("mode") == "numbers" else []
        if not nums:
            ctx["selected_sections"] = {"type": "all", "keys": [c.get("key") for c in catalog if c.get("key")]}
            state.context = ctx
            return

        picked: List[str] = []
        for n in nums:
            idx = int(n) - 1
            if 0 <= idx < len(catalog):
                k = catalog[idx].get("key")
                if k:
                    picked.append(k)

        if not picked:
            picked = [c.get("key") for c in catalog if c.get("key")]

        ctx["selected_sections"] = {"type": "picked", "keys": picked}
        state.context = ctx

    # ----------------------------
    # Final answer generation (LLM JSON)
    # ----------------------------
    def _call_llm_json(self, prompt: str, max_retries: int = 2, state: Optional[ConversationState] = None) -> dict:
        last_err = None
        for _ in range(max_retries):
            try:
                resp = llm_invoke(self.llm, [HumanMessage(content=prompt)], logger=_LOG, label="Academic/json", state=state)
                text = (resp.content or "").strip()

                if "```json" in text:
                    text = text.split("```json")[1].split("```")[0].strip()
                elif "```" in text:
                    text = text.split("```")[1].split("```")[0].strip()

                obj = json.loads(text)
                return obj if isinstance(obj, dict) else {}
            except Exception as e:
                last_err = e
                continue

        if last_err:
            _LOG.warning("[Academic] LLM JSON parse failed: %s", last_err)

        return {
            "input_type": "new_question",
            "analysis": "LLM JSON parse failed",
            "action": "answer",
            "execution": {
                "answer": "ขอโทษครับ ตอนนี้ยังสรุปคำตอบที่ยืนยันได้จากเอกสารไม่ได้",
                "context_update": {"auto_return_to_practical": True},
            },
        }

    def _build_final_prompt(self, state: ConversationState, user_question: str) -> str:
        ctx = state.context or {}
        slots = ctx.get("academic_slots") or {}
        selected = ctx.get("selected_sections") or {"type": "all", "keys": []}

        docs_json = []
        for d in (state.current_docs or [])[:20]:
            md = d.get("metadata", {}) or {}
            docs_json.append(
                {
                    "metadata": {k: ("" if v is None else str(v)) for k, v in md.items()},
                    "content": (d.get("content", "") or "")[:250],
                }
            )

        return f"""
{SYSTEM_PROMPT_ACADEMIC}

USER_QUESTION:
{user_question}

SLOTS:
{json.dumps(slots, ensure_ascii=False, indent=2)}

SELECTED_SECTIONS:
{json.dumps(selected, ensure_ascii=False, indent=2)}

DOCUMENTS ({len(state.current_docs or [])} found):
{json.dumps(docs_json, ensure_ascii=False, indent=2)}

Return JSON:
""".strip()

    def _finalize_answer(self, state: ConversationState) -> str:
        # P0: Always use academic_question (never use slot reply)
        ctx = state.context or {}
        uq = (ctx.get("academic_question") or "").strip()

        if not uq:
            if hasattr(state, "get_last_retrieval_query"):
                uq = (state.get_last_retrieval_query() or "").strip()
            else:
                uq = (state.last_retrieval_query or "").strip()

        uq = uq or getattr(conf, "DEFAULT_RETRIEVAL_FALLBACK_QUERY",
                           "กฎหมายร้านอาหาร ใบอนุญาต ภาษี VAT จดทะเบียน สุขาภิบาล ประกันสังคม")

        prompt = self._build_final_prompt(state, user_question=uq)
        decision = self._call_llm_json(prompt, state=state)

        ex = (decision.get("execution") or {})
        ans = (ex.get("answer") or "").strip()
        if not ans:
            ans = "ขอโทษครับ ตอนนี้ยังไม่พบข้อมูลที่ยืนยันได้ในเอกสาร"

        cu = ex.get("context_update", {})
        if isinstance(cu, dict) and cu:
            state.context.update(cu)

        self._mark_done(state)

        # clean transient
        state.context["pending_options"] = {}
        state.context["pending_question"] = ""
        state.context.pop("resolved_selection", None)

        return ans

    # ----------------------------
    # ENTRYPOINT
    # ----------------------------
    def handle(
        self,
        state: ConversationState,
        user_input: str,
        force_intake: bool = False,
        _internal: bool = False,
    ) -> Tuple[ConversationState, str]:
        state.context = state.context or {}
        state.persona_id = self.persona_id

        # DEDUPE: supervisor already appends user; but allow standalone usage too
        if not _internal:
            self._append_user_once(state, user_input)

        user_text = (user_input or "").strip()

        flow = self._get_flow(state)
        stage = (flow.get("stage") if isinstance(flow, dict) else "") or ""

        # -----------------------
        # Start intake (NO implicit idle stage)
        # -----------------------
        if not stage:
            # If force-routed here but got greeting/noise/blank -> ask for question (no flow created)
            if force_intake and self._looks_like_greeting_or_noise(user_text):
                msg = "อยากให้ช่วยเรื่องไหนเกี่ยวกับกฎหมาย/ขั้นตอนของร้านอาหารครับ"
                self._append_assistant(state, msg)
                return state, msg

            # If there's a real question -> start intake + retrieve once
            if user_text:
                self._start_intake_with_retrieval(state, user_question=user_text)

                # C2: Pre-populate academic_slots from cross-persona slot memory (no re-asking)
                if hasattr(state, "get_collected_slots"):
                    known_slots = state.get_collected_slots()
                    if known_slots:
                        ctx = state.context or {}
                        existing = ctx.get("academic_slots") or {}
                        if not isinstance(existing, dict):
                            existing = {}
                        for k, v in known_slots.items():
                            if k not in existing:
                                existing[k] = v
                        ctx["academic_slots"] = existing
                        state.context = ctx

                self._ensure_flow(state, stage="awaiting_slots")
                q = self._ask_required_slots(state)

                if not q:  # All slots already known or question specific — skip to sections
                    q2 = self._ask_sections(state)
                    if not q2.strip():  # No sections found — finalize immediately
                        ans = self._finalize_answer(state)
                        self._append_assistant(state, ans)
                        state.round = 0
                        return state, ans
                    self._append_assistant(state, q2)
                    state.round = int(getattr(state, "round", 0) or 0) + 1
                    return state, q2

                self._append_assistant(state, q)
                state.round = int(getattr(state, "round", 0) or 0) + 1
                return state, q

            msg = "อยากให้ช่วยเรื่องไหนเกี่ยวกับกฎหมาย/ขั้นตอนของร้านอาหารครับ"
            self._append_assistant(state, msg)
            return state, msg

        # Refresh stage
        flow = self._get_flow(state) or {}
        stage = (flow.get("stage") or "").strip()

        # -----------------------
        # Stage: awaiting_slots
        # -----------------------
        if stage == "awaiting_slots":
            # force_intake: greeting/noise must re-ask slots and keep stage
            if force_intake and self._looks_like_greeting_or_noise(user_text):
                q = self._ask_required_slots(state)
                self._append_assistant(state, q)
                return state, q

            # If empty/garbage -> re-ask
            if not user_text or self._looks_like_greeting_or_noise(user_text):
                q = self._ask_required_slots(state)
                self._append_assistant(state, q)
                return state, q

            # Otherwise treat as slot answer (do NOT retrieve again here)
            self._save_slots_best_effort(state, user_text)

            q2 = self._ask_sections(state)

            # P0: If no sections -> finalize immediately
            if not q2.strip():
                ans = self._finalize_answer(state)
                self._append_assistant(state, ans)
                state.round = 0
                return state, ans

            self._append_assistant(state, q2)
            state.round = int(getattr(state, "round", 0) or 0) + 1
            return state, q2

        # -----------------------
        # Stage: awaiting_sections -> final answer
        # -----------------------
        if stage == "awaiting_sections":
            bind = self._bind_choice_if_any(state, user_text)

            # If user sends noise here, re-ask section menu (keep stage)
            if not user_text or (not bind.get("bound") and self._looks_like_greeting_or_noise(user_text)):
                msg = (state.context or {}).get("pending_question") or self._ask_sections(state)
                msg = msg.strip() or "พิมพ์เลขข้อที่ต้องการ (เช่น 1, 2) หรือพิมพ์เลขข้อสุดท้ายเพื่อดูทั้งหมดครับ"
                self._append_assistant(state, msg)
                return state, msg

            self._save_selected_sections(state, user_text, bind)

            ans = self._finalize_answer(state)
            self._append_assistant(state, ans)
            state.round = 0
            return state, ans

        # Stage done or unknown: safe fallback
        fallback = "ขอโทษครับ ผมยังไม่เข้าใจ รบกวนอธิบายเพิ่มอีกนิดได้ไหมครับ"
        self._append_assistant(state, fallback)
        return state, fallback